name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * 6" # This will run every Saturday at 00:00 UTC
  workflow_dispatch: # This allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git config --global diff.colormoved default
          git config --global diff.renames copies
          git config --global diff.submodule log
          git config --global diff.algorithm histogram

          git config --global core.quotepath false
          git config --global core.precomposeUnicode true
          git config --global status.submoduleSummary true
          git config --global log.date human
          git config --global merge.conflictstyle diff3
          git config --global merge.tool opendiff
          git config --global merge.renameLimit 0
          git config --global help.autocorrect 1
          git config --global transfer.fsckObjects true
          git config --global push.default current
          git config --global push.followTags true
          git config --global push.autoSetupRemote true
          git config --global pull.ff only
          git config --global pull.default current
          git config --global checkout.defaultRemote origin
          git config --global rebase.autoSquash true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global fetch.pruneTags true
          git config --global stash.showPatch true
          git config --global branch.sort -committerdate
          git config --global submodule.recurse true
          git config --global protocol.version 2

      - name: Check if upstream remote exists
        run: |
          set -e
          if ! git remote | grep -q "upstream"; then
            git remote add upstream https://github.com/go-gost/gost.git
          fi

      - name: Fetch upstream
        run: |
          git fetch upstream master
          git merge --allow-unrelated-histories --no-edit upstream/master || exit 1

      - name: Push
        run: |
          git push
